name: Build and Deploy Quarkus Project with Gradle

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: senior-project-364818
  SERVICE_NAME: general-backend
  REGION: asia-east1
  CONTAINER_REGISTRY: gcr.io/$PROJECT_ID

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew build -Dquarkus.package.type=uber-jar

    - name: Configure Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: _json_key
        password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/quarkus-demo:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@main
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ env.CONTAINER_REGISTRY }}/quarkus-demo:${{ github.sha }}
        region: ${{ env.REGION }}
        project_id: ${{ env.PROJECT_ID }}
        platform: managed
        max_instances: 1
        timeout: 300

