name: Build and Deploy Quarkus Project with Gradle

on:
  push:
    branches:
      - master

env:
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  SERVICE_NAME: general-backend
  REGION: asia-east1
  IMAGE_NAME: general-backend
  IMAGE_TAG: ${{ github.sha }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Configure Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: _json_key
        password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Build container image
      env:
        QUARKUS_CONTAINER_IMAGE_NAME: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
        QUARKUS_CONTAINER_IMAGE_TAG: ${{ env.IAMGE_TAG }}
      run: |
        ./gradlew build -Dquarkus.container-image.build=true

    - name: log show images
      run: docker images

    - name: tag image
      run: docker tag runner/${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:1.0.0-SNAPSHOT ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: push image
      run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: login gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: redeploy cloud run
      run: gcloud run deploy ${{ env.SERVICE_NAME }} --project ${{ env.PROJECT_ID }} --region ${{ env.REGION }} --image ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
